version: '3'
services:
    jenkins:
        image: jenkins/docker
        container_name: jenkins
        build:
            context: .
        ports:
          -  "8081:8080"
          -  "50000:50000"
        volumes:
          - ./jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
