version: '3'
services:
    quboo-backend:
        container_name: quboo-backend
        image: "mechero/quboo-backend"
        environment:
          SPRING_DATA_MONGODB_HOST: mongo
          GAME_DATES_LEGACY: "${LEGACY_DATE}"
          GAME_DATES_EARLYBIRD: "${EARLYBIRD_DATE}"
          GAME_DATES_CAMPAIGNSTART: "${CAMPAIGNSTART_DATE}"
          GAME_CODE: "${QUBOO_CODE}"
          SONAR_SERVER: "${SONAR_SERVER}"
          SONAR_ORGANIZATION: "${SONAR_ORGANIZATION}"
          SONAR_TOKEN: "${SONAR_TOKEN}"
        ports:
          - "8080:8080"
    quboo-web-client:
        container_name: quboo-web-client
        image: "mechero/quboo-web-client"
        ports:
          - "1827:1827"
